name: Notify start deploy to Rollbar

on: 
  push:
    branches: [main]
  
jobs:
  deploy:
    # needs: eslint
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Notify start deploy to Rollbar
      uses: rollbar/github-deploy-action@2.1.1
      id: rollbar_pre_deploy
      with:
        environment: 'production'
        version: ${{ github.sha }}
        status: 'succeeded'
      env:
        ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
        ROLLBAR_USERNAME: stangogh